---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: security-profiles-operator
    newName: gcr.io/k8s-staging-sp-operator/security-profiles-operator
    newTag: latest
    # For images to be released, use the `k8s.gcr.io` registry:
    # newName: k8s.gcr.io/security-profiles-operator/security-profiles-operator
    # newTag: v0.3.0

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: security-profiles-operator
    namespace: security-profiles-operator
  spec:
    template:
      spec:
        containers:
          - name: security-profiles-operator
            env:
              - name: RELATED_IMAGE_NON_ROOT_ENABLER
                # For images to be released, use the `k8s.gcr.io` registry:
                # value: k8s.gcr.io/security-profiles-operator/non-root-enabler:v0.3.0
                value: gcr.io/k8s-staging-sp-operator/non-root-enabler:latest
              - name: RELATED_IMAGE_SELINUXD
                value: quay.io/jaosorior/selinuxd

commonLabels:
  app: security-profiles-operator

resources:
  - crd.yaml
  - rbac.yaml
  - operator.yaml
  - config.yaml

configMapGenerator:
  - name: security-profiles-operator-profile
    files:
      - profiles/security-profiles-operator.json

generatorOptions:
  disableNameSuffixHash: true
