---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: seccomp-operator
    newName: gcr.io/k8s-staging-seccomp-operator/seccomp-operator
    newTag: latest
    # For images to be released:
    # newName: k8s.gcr.io/seccomp-operator/seccomp-operator
    # newTag: v0.2.0

  - name: bash
    newTag: "5.0"

commonLabels:
  app: seccomp-operator

resources:
  - operator.yaml
