
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: spo-manager
rules:
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - selinuxpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - selinuxpolicies/finalizers
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - selinuxpolicies/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: spo-manager
  namespace: security-profiles-operator
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: spod
rules:
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - seccompprofiles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - seccompprofiles/finalizers
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - seccompprofiles/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: spod
  namespace: security-profiles-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
