---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spo-manager
  namespace: security-profiles-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spod
  namespace: security-profiles-operator